Ports TV-camera assembly from Bay
PolarisSS13/Polaris pull request #7737
Opened 2020-10-18 01:24 UTC by Runa-Dacino

Copies https://github.com/Baystation12/Baystation12/pull/14875

I've recently noticed downstream you can't build TV Camera drones on demand.

How to build drones:

1. Get Robot head
2. Infrared sensor -> Makes the assembly. Looks like robot head.
3. Add robot camera
4. Add Tape recorder
5. Add 3 wires
6. Use wirecutters on assembly
7. Add 1 steel
8. Done

2020-10-18 12:18 UTC, Meghan-Rossi commented on code/game/objects/items/devices/tvcamera.dm
> +	w_class = ITEM_SIZE_LARGE
ITEMSIZE_LARGE

2020-10-18 12:18 UTC, Meghan-Rossi commented on code/game/objects/items/devices/tvcamera.dm
> +			if(istype(W, /obj/item/weapon/wirecutters))
It's /obj/item/weapon/tool/wirecutters, except that that doesn't account for jaws of life.  if(W.is_wirecutter()) would account for that.

2020-11-16 21:09 UTC, Shadow-Quill commented
Still needs to be updated

2020-11-16 21:11 UTC, Shadow-Quill requested changes

2020-11-16 21:11 UTC, Shadow-Quill commented on code/game/objects/items/devices/tvcamera.dm
> +	if ((!istype(S, /obj/item/device/assembly/infra)))
Extraneous parentheses here

2020-11-30 23:01 UTC, Runa-Dacino commented
Kinda had a sudden splurt of wanting to port this. Forgot about it. Will look at it later, sorry for pointless need for reviews >.>

2020-11-30 23:01 UTC, closed without merging