Boda Tweaks and Russian Drinks
PolarisSS13/Polaris pull request #7939
Opened 2021-03-01 05:24 UTC by klaasjared

Cleans up that old 'Todo' that was tacked onto the Boda Vending Machine code way back when.

Adds three Russian drinks for the Boda Machine and subsequently adds them into the Boda machine.

_Drinks added:_
-Kvass
-Kompot
-Boda (sodawater)

Image of drinks below (cans in order of the list above).

![russian_showcase](https://user-images.githubusercontent.com/609886/109455322-5c3f5d80-7a24-11eb-9ade-bf7062647887.png)

2021-03-04 21:55 UTC, MistakeNot4892 commented
You seem to have included an unrelated arcade machine commit.

2021-03-04 21:55 UTC, MistakeNot4892 commented on code/modules/food/food/cans.dm
> +	desc = "A true slavic soda."
Slavic is a proper noun and should probably be capitalized.

2021-03-04 21:56 UTC, MistakeNot4892 commented on code/modules/food/food/cans.dm
> +	description_fluff = "A classic slavic beverage which many Space Russians still enjoy to this day. Fun fact, it is actually considered a weak beer by Non-russians."
As above, also lowercase n on `Non`.

2021-03-04 21:57 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	description = "A traditional eastern european beverage once used to preserve fruit in the 1980s"
`Eastern European` I think. Not completely sure if `eastern` is part of the noun or not.

2021-03-04 21:58 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	strength = 95 //It's just soda to Russians
Kvass is like 1-2% alcohol by volume compared to beer which is 4-6%. Seems like a bit of a meme to make it double the strength of beer.

2021-03-10 18:50 UTC, Atermonera commented
`polaris.dme:762:error: unable to open "code/game/machinery/computer/arcade.dm".`

2021-03-18 08:11 UTC, Atermonera requested changes

2021-03-18 08:11 UTC, Atermonera commented on code/game/machinery/computer/arcade.dm
> -/obj/machinery/computer/arcade
And now you've outright deleted the whole file as a committed change.

2021-03-18 08:26 UTC, MistakeNot4892 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	strength = 95 //It's just soda to Russians
Discussed on Discord, higher is weaker in alcohol code. Thanks SS13.

2021-03-23 14:27 UTC, closed without merging

2021-03-23 14:28 UTC, klaasjared commented
Forgot to close this one - I'll be redoing it from scratch to fix the file errors