Fixes Medical/Security PDA Records
PolarisSS13/Polaris pull request #8066
Opened 2021-05-05 23:23 UTC by Novacat

This is my first TGUI PR, please be gentle.

2021-05-07 05:55 UTC, stylemistake commented
Here's a suggestion: rename it to `preserveWhiteSpace` and create a similar PR on tgstation (which is the upstream of tgui).

2021-05-07 05:57 UTC, stylemistake commented on tgui/packages/tgui/interfaces/SecurityRecords.js
> +              <Box height="20px" display="inline-block" prewrap>
you can just use the `inline` property instead.

2021-05-09 01:25 UTC, ShadowLarkens requested changes

2021-05-09 01:25 UTC, ShadowLarkens commented on tgui/packages/tgui/components/Box.js
> +  prewrap: mapBooleanPropTo('white-space', 'pre-wrap'),
```suggestion
  preserveWhiteSpace: mapBooleanPropTo('white-space', 'pre-wrap'),
```

2021-05-09 01:25 UTC, ShadowLarkens commented on tgui/packages/tgui/interfaces/GeneralRecords.js
> +        <Section title="Employment/skills summary" level={2} prewrap>
```suggestion
        <Section title="Employment/skills summary" level={2} preserveWhiteSpace>
```

2021-05-09 01:25 UTC, ShadowLarkens commented on tgui/packages/tgui/interfaces/SecurityRecords.js
> +              <Box height="20px" display="inline-block" prewrap>
```suggestion
              <Box height="20px" inline preserveWhiteSpace>
```

2021-05-10 00:25 UTC, Atermonera commented
You'll have to update your branch with the updated CI OS version to get it to pass

2021-05-11 06:58 UTC, merged