Ports Pixel Shifting
PolarisSS13/Polaris pull request #8244
Opened 2021-08-23 19:57 UTC by Cerebulon

CTRL + SHIFT + Movement Keys to scoot around juuuuuust a little.
https://github.com/VOREStation/VOREStation/pull/9265 + various fixes

:cl:
rscadd - Added pixel shift movement. Ctrl+shift+movement key to move around within a single tile.
/:cl:

2021-08-23 20:14 UTC, zekesulastin commented
Aside from the CI failure, it also looks like you didn’t add CTRL+SHIFT+W/A/S/D for hotkey mode :(

2021-08-23 20:31 UTC, Cerebulon commented
> 
> 
> Aside from the CI failure, it also looks like you didn’t add CTRL+SHIFT+W/A/S/D for hotkey mode :(

NORTH, SOUTH, EAST and WEST should reference the actual movement keys afaik?

2021-08-24 00:01 UTC, zekesulastin commented
> 
> 
> > Aside from the CI failure, it also looks like you didn’t add CTRL+SHIFT+W/A/S/D for hotkey mode :(
> 
> NORTH, SOUTH, EAST and WEST should reference the actual movement keys afaik?

Nope - they are defined further down in the alphabetical section of the file

2021-08-31 00:08 UTC, MistakeNot4892 commented
Personally I really don't like this feature. It allows you to mess with offsets and interrupt animations for the sake of the minor RP benefit of being to pose yourself. Positioning on turfs can already be a bit confusing and I think this has the potential to make it worse.

Not blocking or anything, but won't be approving this personally. Sort of an abstaining review I guess?

2021-09-03 02:19 UTC, Atermonera commented
This feels like it will introduce a lot of unintuitive behaviour where animations are interrupted or offsets reset unexpectedly. It might introduce weird behaviour in combat from projectile weapon targeting?

2021-09-26 06:05 UTC, Atermonera requested changes

2021-09-26 06:05 UTC, Atermonera commented on code/modules/mob/mob.dm
> +		is_shifted = TRUE
```suggestion
	if(custom_pixel_y < 16)
		pixel_y++
		custom_pixel_y++
```
And so on and so forth.

2021-09-26 06:05 UTC, Atermonera commented on code/modules/mob/living/living_movement.dm
> +		pixel_y = default_pixel_y
By tracking custom offsets independently, we just subtract pixel_x/y by those values and set the tracking vars to 0
```suggestion
if(custom_pixel_x)
	pixel_x -= custom_pixel_x
	custom_pixel_x = 0

if(custom_pixel_y)
	pixel_y -= custom_pixel_y
	custom_pixel_y = 0
```

2021-09-26 06:05 UTC, Atermonera commented on code/modules/mob/mob.dm
> +		is_shifted = TRUE
Also, I'm guessing hotkey macros are why there's 4 separate procs here, and not one that just takes in a DIR?

2022-02-17 08:03 UTC, Atermonera commented
Stale, no plans to work on it due to opposition

2022-03-16 11:04 UTC, Spookerton commented
@Atermonera reopen intended?

2022-04-13 21:29 UTC, Spookerton commented
I will assume not, given a month.

As far as I'm concerned the opposition to this is entirely correct. Being able to do some little pixel shifting to the detriment of numerous other real mechanics is not a good trade.

2022-04-13 21:29 UTC, closed without merging