Expands the material values of certain items.
PolarisSS13/Polaris pull request #8252
Opened 2021-08-27 02:11 UTC by lbnesquik

## About this pull request
This adds some default values to a few extra objects for materials.
This mostly comes into play regarding autolathes and recycling gear.
This also adds a default value of 1 metal to every item which you can reasonably expect to be holding.

## Why is this good for the game
What can be recycled or not along with the exact yields of which are really, really not consistent at all. 
But because it would take ages to go through and make a comprehensive update of material costs, i simply added a few to the more outlandish ones, and given the base tiny value of one to everything.

2021-08-27 23:01 UTC, lbnesquik commented
Screwdrivers already have a metal cost so i doubt that.

2021-08-30 23:41 UTC, MistakeNot4892 commented on code/game/objects/items/apc_frame.dm
> +	matter = list(DEFAULT_WALL_MATERIAL = 100,"glass" = 30)
Please use MAT_STEEL and MAT_GLASS for these and the other lines - DEFAULT_WALL_MATERIAL being used for matter lists was really a mistake in the first place and using bare strings for glass is not ideal.

2021-08-30 23:42 UTC, MistakeNot4892 requested changes
See comment.

2021-08-31 23:54 UTC, MistakeNot4892 approved these changes

2021-09-03 02:19 UTC, merged