Moves a LOT of sprites around.
PolarisSS13/Polaris pull request #8257
Opened 2021-08-28 02:05 UTC by lbnesquik

## About this pull request
This is like a spring-cleaning, but in August. There are more things which are a little odd in our sorting, but this should get the most obvious out of the way.

Here are the details :

- Moved all the screens dmi files to the screen sub folder
- Moved the 'roaper' file to clothing. It isn't actually used anywhere, but it doesn't belong in /mob
- Deleted amorph and bats, moved the respective sprites into mob.dmi
- Deleted eye.dmi and moved the AI eye into AI.dmi. It is simpler to have everything AI related in the same folder.
- Deleted gimmick_head and pilot_helmet.dmi and moved them into head.dmi. Each of those files had only a couple sprites and nothing particularly unique.

2021-08-28 02:46 UTC, MistakeNot4892 commented
Oh Jesus, that `roaper.dmi` is a custom item I committed by accident in like 2014.

2021-08-28 18:34 UTC, lbnesquik commented
> 
> 
> Oh Jesus, that `roaper.dmi` is a custom item I committed by accident in like 2014.

IT WAS YOU

2021-08-30 23:47 UTC, MistakeNot4892 commented
Alright so: 
- `/screen` stuff is all good.
- `roaper.dmi` should just be deleted, not kept around, nothing uses it and iirc the sprite ended up in the voidsuit icons anyway.
- bats and pilot helmet being merged into the giant monolithic DMI files - why? Having everything in one file makes conflicts more likely and is ideally something to move away from, not an improvement.

2021-08-30 23:47 UTC, MistakeNot4892 requested changes
Will approve after deleting roaper.dmi and explaining rationale for the monolith DMI merges.

2021-08-31 22:50 UTC, lbnesquik commented
> 
> 
> Will approve after deleting roaper.dmi and explaining rationale for the monolith DMI merges.

Pilot helmets having their own file for 3 little sprites is silly to me. That's it.

2021-09-01 09:37 UTC, AffectedArc07 commented
Could you stick `[IDB IGNORE]` in the title to make IconDiffBot ignore this PR? The job took 4 minutes to process, which is quite a waste of CPU time when its just reorganisation stuff.
![image](https://user-images.githubusercontent.com/25063394/131648904-a870ebc1-086b-4327-9a0d-c51be2f81a66.png)

2021-09-01 09:44 UTC, MistakeNot4892 commented
Done, apologies, should have occurred to me.

2021-09-06 03:49 UTC, Atermonera requested changes

2021-09-06 03:49 UTC, Atermonera commented on code/modules/clothing/head/pilot_helmet.dm
>  		SPECIES_TESHARI = 'icons/mob/species/teshari/pilot_helmet.dmi'
:+1: on squishing this into the monolith. We have existing infrastructure to split the clothing monolithic .dmi's into multiple (via the `index` var) when they grow too big.

Also, you missed a spot.

2021-09-06 03:49 UTC, Atermonera commented on code/modules/mob/living/simple_mob/subtypes/animal/space/bats.dm
> -	icon = 'icons/mob/bats.dmi'
:-1: on unifying this. Different mobs may have different sets of sprites, so it doesn't necessarily make sense to group all [generic] mob sprites into a single file. We also don't have the infrastructure or expectations of clothing, so the differentiation in icon file comes from the assignment of the icon var itself. This is a lot less intuitive unless there's logical separation in the naming of the .dmi files used.

And I actually think our `icons/` folder hierarchy needs more depth. If you _must_ change this, make an animals dmi, and move this along with other animal simplemob sprites into it. Or create an animals subdir, and split other animal simplemob sprites off of the monolith. (Latter is very much preferred)

Yes, this is a different answer than for clothing, but clothing sprites are much more complicated, and adjusting them in a similar manner according to their existing infrastructure will be a fair bit more involved.

2021-09-11 11:17 UTC, closed without merging