HE pipe turf interaction
PolarisSS13/Polaris pull request #8409
Opened 2022-02-26 17:43 UTC by TheLordME

Yes hello, I was inspired by the water turf under the HE pipes to make this PR.
I have implemented exactly these changes on CitRP, and its probably the best way to do it zone bases atmos.

I know that its my master branch, whoopsie on my end, havent tested it localy, but as I said, it works fine on CitRP, where it has been full merged for some time now, without any major issues.

the relavant PRs are:
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/3614
and
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/3651

2022-02-26 18:59 UTC, Atermonera submitted a review, later dismissed

2022-03-18 16:43 UTC, Spookerton requested changes

2022-03-18 16:43 UTC, Spookerton commented on code/ATMOSPHERICS/pipes/he_pipes.dm
> +			if((abs(environment_temperature-pipe_air.temperature) > minimum_temperature_difference) || (location_as_turf.special_temperature))
```suggestion
			var/turf/loc_as_turf = loc
			if((abs(environment_temperature-pipe_air.temperature) > minimum_temperature_difference) || (loc_as_turf.special_temperature))
```

2022-03-30 11:15 UTC, Spookerton requested changes

2022-03-30 11:15 UTC, Spookerton commented on code/ATMOSPHERICS/pipes/he_pipes.dm
> +			var/turf/loc_as_turf = loc
```suggestion
			var/turf/simulated/loc_as_turf = loc
```
My bad. I didn't check what level you defined special_temperature.

2022-04-19 12:28 UTC, Spookerton commented
@TheLordME Beep.

2022-04-19 12:48 UTC, TheLordME commented
Gonna push the changes in ~ 3 hours

2022-04-19 21:26 UTC, Spookerton approved these changes

2022-04-19 21:28 UTC, Spookerton commented
Code do the thing. @Atermonera had an approval on the prior failing code; I assume that's conceptual.

2022-04-20 05:29 UTC, merged