Adds Hairnets
PolarisSS13/Polaris pull request #8441
Opened 2022-03-17 18:50 UTC by Cerebulon

In loadout (recolourable) and in the kitchen locker. Now you can look like a real lunch lady instead of a fancy french chef _and_ keep your hair out of the damn food.

From: https://github.com/Aurorastation/Aurora.3/pull/12860

2022-03-18 14:59 UTC, Spookerton requested changes

2022-03-18 14:59 UTC, Spookerton commented on code/modules/clothing/head/jobs.dm
> +		SPECIES_TAJARAN = 'icons/mob/species/tajaran/head.dmi'
```suggestion
		SPECIES_TAJARAN = 'icons/mob/species/tajaran/helmet.dmi'
```

2022-03-18 16:33 UTC, Spookerton approved these changes
does the thing

2022-03-20 19:17 UTC, Atermonera approved these changes

2022-03-24 12:34 UTC, Spookerton approved these changes

2022-04-01 17:32 UTC, merged