Adds more alien organ sprites
PolarisSS13/Polaris pull request #8442
Opened 2022-03-17 20:33 UTC by Cerebulon

Skrell Everything (blue-green). Moved spleen into correct file.
Unathi eyes (already had filt. organ and heart)
Tajaran liver, stomach and lungs (look funkier)
Fixed dead unathi hearts being invisible

2022-03-18 14:57 UTC, Spookerton requested changes

2022-03-18 14:57 UTC, Spookerton commented on code/modules/organs/subtypes/tajaran.dm
> +	icon_state = "tajaran_liver"
```suggestion
	icon_state = "tajaran_stomach"
```

2022-03-18 16:28 UTC, Spookerton approved these changes
skrell didn't turn to goo on creation; does the thing

2022-03-20 19:22 UTC, Atermonera commented
~new mmi sprite when~

2022-03-20 19:22 UTC, merged