Adds Preference for Graffiti Engraving
PolarisSS13/Polaris pull request #8524
Opened 2022-04-11 07:06 UTC by Cerebulon

Meant to do this a while ago. Saw downstream's half-fixes and compensations for those half fixes and just... Did the sensible thing and added a toggle.

The pref is on by default.
When on, it behaves as it currently does, engraving with sharp objects on hard surfaces (floor/wall) happens on help intent.
When off, sharp object + help intent = nothing, no accidental clickies.
~~Regardless of preference, you can alt click on a hard surface (floor/wall) with a sharp object and do an engraving that way.~~

It's also extremely funny that you can engrave with syringes but that's something for another day.

2022-04-12 20:04 UTC, Sypsoti commented
As voiced to you already, I don't think Alt click functions should be included. I used alt-click to view tiles and I don't want to start engraving from that. Unless anyone has a strong reason that should remain, I'd like to see it removed. The toggle is fine.

2022-04-13 21:15 UTC, Spookerton requested changes

2022-04-13 21:15 UTC, Spookerton commented on code/game/turfs/simulated/wall_attacks.dm
> +	. = ..()
```suggestion
```

Alt-clicking to view tile contents is a long standing and dramatically more useful behavior. Intercepting it this way is a mistake.

2022-04-16 10:44 UTC, Spookerton approved these changes

2022-04-16 10:45 UTC, merged