A -ton of Flags
PolarisSS13/Polaris pull request #8721
Opened 2022-10-01 10:56 UTC by Cerebulon

SCG, VGA, NT, Five Arrows, Both Almachs, Vystholm, and the four big political parties.
For mapping/admin use currently. Base sprite and basis of code from Aurora.

2022-10-01 12:23 UTC, Greenjoe12345 commented on code/game/objects/structures/signs.dm
> +	name = "Almach Protectorate flag"
Wrong name here

2022-10-07 06:13 UTC, Spookerton requested changes

2022-10-07 06:13 UTC, Spookerton commented on code/game/objects/structures/signs.dm
> +	flag_path = "pirate""
```suggestion
	flag_path = "pirate"

```

2022-10-07 08:49 UTC, Cerebulon commented
Hey that was a load bearing extra " that was holding up another extra "! (fixed)

2022-10-07 10:38 UTC, Spookerton approved these changes

2022-10-07 20:09 UTC, merged