Basic Uniform Polish: Engineering
PolarisSS13/Polaris pull request #8743
Opened 2022-10-10 23:40 UTC by Cerebulon

...And some assistants. Doing this in stages because it's a lot and some of the default uniforms might actually need more significant redesigns than this.

Mechanical tweaks:

- Added engineering overalls. Equivalent to webbing vests.
- Hazard vests can be toggled open/closed.

Sprites:

- Replacements for the basic uniform sprites for Engineer, Atmos Tech and CE.
- Less garish hard hat and hazard vests. But still bright!
- New uniforms are NT branded.

Default loadouts:

- Atmos techs now start with a blue hazard vest and hard hat.
- Engineers now start with an orange hazard vest.
- CE starts with white overalls attached to a jumpsuit.
- Assistants start with an 'assistant jumpsuit', which is far more visually similar to the old grey jumpsuit than the recently added dark-grey.
- Technical assistants start with a version of the assistant jumpsuit with small yellow accents.
- Both types of engineering lockers start with engineer overalls.

The visual differences are ultimately pretty minor, just colour and shading changes for the mostpart. 90% of people replace the defaults anyway, but there's no reason for the defaults to be ancient primary-coloured sprites!
Hard hats, accessory-overalls, and some hazard vests via Aurora. Adjustments to those, and other sprites by me.

2022-10-11 00:14 UTC, Greenjoe12345 commented
the tesh version of the hardhats will want a slight edit so they're not wonky on teshari heads, due to the funkyness of teshari sprites (like how the old ones had two pixels in the middle vs one the new ones have)

2022-10-12 23:43 UTC, Spookerton approved these changes

2022-10-13 09:26 UTC, Spookerton requested changes
needs conflict resolution; suggest waiting on #8740 since this will conflict with that as well.

2022-10-17 09:45 UTC, Spookerton approved these changes

2022-10-17 09:46 UTC, merged