Naming Food & Blood Cakes
PolarisSS13/Polaris pull request #8817
Opened 2022-11-05 15:21 UTC by Mechoid

:cl:
bugfix - Fix reagent-only custom foods being grey and nameless. Down with grey cake. In with blood cake.
adds - Ability to Alt-Click food items to rename them. Giving an invalid or blank name will reset it.
/:cl:

[img]https://i.imgur.com/3EB2WYE.png[/img]

2022-11-07 12:44 UTC, Spookerton requested changes
Overriding alt-click behavior is very much to be avoided because it is the shortcut for the tile contents list- renaming should be a verb.

2022-11-07 12:46 UTC, Spookerton commented
Aside, please try to avoid merging the main branch into feature branches; update your main and rebase against it instead. This keeps git history cleaner and more understandable.

2022-11-07 13:48 UTC, Spookerton submitted a review, later dismissed

2022-11-07 13:48 UTC, Spookerton commented on code/modules/food/food.dm
> +	description_info = "Food can be alt-clicked to rename it."
```suggestion
	description_info = "Food can use the Rename Food verb in the Object Tab to rename it."
```

2022-11-11 06:49 UTC, Atermonera approved these changes

2022-11-11 06:49 UTC, merged