End of 2022 item addition
PolarisSS13/Polaris pull request #8864
Opened 2022-12-24 02:10 UTC by Greenjoe12345

This adds several new items:
two new styles of communicator, one based on a flip phone and one based on a old nokia kinda design.
a folding white cane, and a telescopic walking cane.
![image](https://user-images.githubusercontent.com/33647525/209417715-d9f0c9f7-4735-4a7c-855d-735e2014c532.png)

2022-12-24 03:40 UTC, Cerebulon commented
I think it was generally be a good idea to just name these PRs something more descriptive like "Alternative communicator and cane sprites" because "2022 end item additions" sounds like some massive overhaul and this is essentially just a couple of sprites.

2022-12-24 04:54 UTC, Greenjoe12345 commented
Fair enough

2023-01-02 23:52 UTC, Atermonera requested changes
Sorry for my tardiness here, last week was pretty busy.

2023-01-02 23:52 UTC, Atermonera commented on code/game/objects/items/devices/communicator/communicator.dm
> +		icon_state = "commflip-video"
Use `"[initial(icon_state)-video"` in the parent type for these?

2023-01-02 23:52 UTC, Atermonera commented on code/modules/client/preference_setup/loadout/loadout_general.dm
> +/datum/gear/cane/telescopic
Gear-selection datum for all the subtypes of cane?

2023-01-03 00:32 UTC, Greenjoe12345 commented
I've done those adjustments.

2023-01-03 00:37 UTC, Atermonera approved these changes

2023-01-03 02:19 UTC, merged