Teshari/Skrell food expansion
PolarisSS13/Polaris pull request #8888
Opened 2023-01-18 04:48 UTC by Greenjoe12345

This PR adds a number of Sirisaian/Quer'balakian plants and foods, available to grow and cook, a number aimed towards teshari, and a number towards Skrell.
This will want a wiki update when it's in.
the recipes are as follows

DRINKS

Dyn tea = 1 dyn juice, 4 water = 5 dyn tea

Dyn iced tea = 1 dyn juice, 2 ice, 2 soda water = 5 dyn iced tea

FOOD

Dyn soup - MICROWAVE = 10 water, 2 dyn, 1 cabbage, 1 tomato

Zantiri - MICROWAVE = 10 water, 2 guami, 1 eki

Lortl - Oven = 1 q'lort, 1 salt = 3 lortl

Boiled fjylozyn - MICROWAVE = 1 fjylozyn, 5 water

Neaera stew - MICROWAVE = 10 dyn juice, 10 water, 2 guami, 2 eki, 1 Neaera meat

Candied Neaera eyes - OVEN = 5 cream, 1 dough, 1 neaera eyes = 6 candies

Neaera kebab - MICROWAVE = 1 Neaera meat, 1 Neaera kidney, 1 metal rod

Garani - FRYER = 2 boiled fjylozyn, 1 Neaera liver

Qa'zal bread - OVEN = 4 qa'zal dough

Grilled qa'zal flatbread - GRILL = 1 flat qa'zal dough

Baked ga'uli - OVEN = 1 ga'uli

Baked kirani - OVEN = 1 kirani

Stuffed ga'uli = OVEN = 1 ga'uli, 1 kirani, 1 Neaera meat

Kirani stew - MICROWAVE = 10 kirani jelly, 1 qa'zal, 1 Neaera meat

Qa'zal noodles - MICROWAVE = 1 kirani, 1 gu'ali, 3 Qa'zal dough strips

Kirani jellypuff - OVEN = 2 Qa'zal dough, 5 kirani jelly, 5 qa'zal flour

qa'zal dough = 10 qu'zal flour, 5 ga'uli juice

2023-01-18 12:34 UTC, Cerebulon commented
Will also need review from skrellmaint who incidentally is also Ater so, handy!
Only notes from me:
"fjylozyn" does not really seem to match with skrell phonemes and could probably use a skrellier name to avoid confusion with sif style scandigarble
Not sure about All the exotic skrell seeds being available in seedvend? Up to ater.
You dont need to denote and date new additions to the food file. People have done it in the past but it seeeems to be a virgo thing or something and just needs cleaning up later? git blame does dating and attributing automatically and better anyway.
Also is this stuff From another server? Very mild concern about straight lore transplants. None of it seems conflicty its just a distinctiveness thing if the names/concepts are direct lifts.

2023-01-18 12:59 UTC, Greenjoe12345 commented
The stuff is from other servers, Yes, I did alter some stuff about them that wasn't fitting for here.
As for fjylozyn, I'll see about altering the name on that, maybe something like 'qa'lozyn'

2023-01-30 07:48 UTC, Atermonera requested changes
Lore PRs relating to skrell mean I might actually be particular about syntax and grammar.

2023-01-30 07:48 UTC, Atermonera commented on code/modules/reagents/reagents/food_drinks.dm
> +	description = "Juice from a Qerr'balakian herb. Good for you, but normally not consumed undiluted."
```suggestion
	description = "Juice from a Qerr'balakian herb. Good for you, but usually diluted for potability."

2023-01-30 07:48 UTC, Atermonera commented on code/modules/reagents/reagents/food_drinks.dm
> +	description = "An old-fashioned, but traditional skrellian drink with documented medicinal properties."
```suggestion
	description = "A traditional skrellian drink with documented medicinal properties."

2023-01-30 07:48 UTC, Atermonera commented on code/modules/reagents/reagents/food_drinks.dm
> +	description = "Harvested from ground qa'zal, this is one of the main ingriedents in qa'zal bread."
```suggestion
	description = "Harvested from ground qa'zal, this is one of the main ingredients in qa'zal bread."

2023-01-30 07:48 UTC, Atermonera commented on code/modules/reagents/reagents/food_drinks.dm
> +	description = "Juice from a ga'uli pod, used within skrell and teshari cooking."
```suggestion
	description = "Juice from a ga'uli pod, used in skrellian and teshari cooking."

2023-01-30 16:11 UTC, Greenjoe12345 commented on code/modules/food/food/snacks.dm
> +	desc = "A candied neaera eye shaped into a cube. The mix of savoury and sweet is generally acceptable for most species, although the dish is not commonly liked due to the use of eyes."
This item's referring to a single candy, so it referring to a single one is right, I'd think?

2023-02-06 00:30 UTC, Atermonera approved these changes

2023-02-06 00:31 UTC, merged