Drake harnesses are removable.
PolarisSS13/Polaris pull request #8904
Opened 2023-01-27 19:08 UTC by MistakeNot4892

- Drake harnesses can be removed and replaced, and exist as items in the world.
- Various drake logic has been merged down to either base animal harness level, or base drake level.

DNM, still getting harness removal/replacement to work.

Depends on #8922 #8923

2023-01-29 20:24 UTC, Spookerton commented
Noting in general that runechat doesn't like html, but that's systemic and a nightmare all its own.
![https://i.imgur.com/fnfbOqT.png](https://i.imgur.com/fnfbOqT.png)

2023-01-29 20:40 UTC, Spookerton requested changes

2023-01-29 20:40 UTC, Spookerton commented on code/modules/mob/living/simple_mob/subtypes/animal/sif/grafadreka/grafadreka_misc.dm
> +	emote_message_3p_target = "stares intently at TARGET, working USER_HIS throat to make a horrible wet noise..."
```suggestion
	emote_message_3p = "works USER_THEIR throat, making a horrible wet noise..."
	emote_message_3p_target = "stares intently at TARGET, working USER_THEIR throat to make a horrible wet noise..."

```

2023-03-09 02:04 UTC, Atermonera approved these changes

2023-03-09 02:04 UTC, merged