clothes port January-February 23
PolarisSS13/Polaris pull request #8921
Opened 2023-02-02 17:59 UTC by Greenjoe12345

Ports a number of clothing items from skyrat, aurora, bay and urist.
Some new utility jumpsuits
New headphone variations, plus replacing the sprites of the old headphones with recolorable ones
Some winter gear; mittens, wooly hats, ear warmers
Waist bags that can be worn on the belt slot
A hide oversuit that offers protection against the cold

2023-02-02 18:37 UTC, Cerebulon commented
I'd very much suggest at least re-describing the "utility uniforms" because:
The old old old "utility uniform" that the description is based on is actually a turtleneck utility thing <s>which is probably based on Mission Impossible or something.</s> Frankly it shouldn't be called a utility uniform but 'tactical turtleneck' was taken.
These on the other hand, are not turtlenecks with utility pants. These are jumpsuits/coveralls (SS13 calls coveralls 'jumpsuits' for 1970s reasons, but I digress). The slightly less old "utility uniforms" (blue and grey) are jumpsuits, and should be what you're basing the descriptions on.
_Personally_ I think they look less "utility" than the newer basic jumpsuit sprites so would call (and path) them something like "[department] accented jumpsuit" and that the old "utility" uniforms are only called that because they were meant to be like military flight suits or something.

I'm also a little meh about the earphones/earbuds on the basis of them being ultra-2020s and the existing headphones being the same retro-bulky concept as Jumpsuits but apparently that's a losing battle on my part and not up 2 me ultimately.

2023-02-02 19:08 UTC, Sypsoti requested changes
A few changes needed, and I'm kind of wanting to keep the colored musical notes for the on-mob sprites for headphones. I specifically changed it in the past due to complaints about readability.

2023-02-02 19:08 UTC, Sypsoti commented on code/modules/clothing/ears/ears.dm
> +	volume_multiplier = 0.7 //not designed to block sound like earmuffs but still covers over the ears, so blocks sound a bit
Could probably just be a child of earmuffs at this point.

2023-02-02 19:08 UTC, Sypsoti commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "A comfortable turtleneck and black utility trousers. This one has accents in the supply department's color."
I believe cerebul had words about this description being odd paired with the sprite, so please correct that as well.

2023-02-02 19:25 UTC, Greenjoe12345 commented on code/modules/client/preference_setup/loadout/loadout_ears.dm
> +	gear_tweaks += gear_tweak_free_color_choice
![image](https://user-images.githubusercontent.com/33647525/216429878-dc1c30c7-0451-4acb-a778-5a9bcbe95e68.png)
![image](https://user-images.githubusercontent.com/33647525/216429903-e9147cec-dfee-4df4-a4f8-96b0ef3258bf.png)
works just fine

2023-02-03 19:52 UTC, Cerebulon commented
Imo the belts should definitely still cost 2 and 3 **minimum**, not 1.
2 is the relatively standard cost for a thing with mechanical advantages and these are literally Universal Belts with potentially more capacity than simple webbing. Which costs 2. Given half the station don't always have job belts (which have a restricted list of things you can put on them!!) there needs to be literally any reason not to take these and have 4+ extra pockets which is some potentially dumb loadout power creep.
<s>I'm not going to get into huge arguments about how it should be higher and the big ones should be maint/wilderness spawns because loadout balance is a mess so the standard 2 is probably all I'm going to get.</s>

2023-02-04 20:43 UTC, Spookerton commented
Drafted. Needs CR and conflict resolution.

2023-02-06 12:25 UTC, Cerebulon commented
From the staff meeting on 5th Feb:
Waist packs are a little too power creep-y, so:

1. Small waist pack and fannypack should cost 2 points
2. Large waist pack should be removed from loadout and added to maintenance random-spawners alongside dufflebags.

2023-02-22 04:11 UTC, Atermonera commented
@Greenjoe12345 merge conflicts

2023-02-22 13:24 UTC, Greenjoe12345 commented
Yeah gonna see about getting to fixing when I can

2023-10-12 16:21 UTC, closed without merging