[DNM] [Requested] Serenity changed to proper medical exosuit.
PolarisSS13/Polaris pull request #8951
Opened 2023-02-14 05:03 UTC by Mechoid

Will be discussed at staff meeting, PR made by request.

Serenity tweaked to be a medical subtype, weapons cannot fit in universal slots.

Serenity weapon slot converted to a hull slot.

Exosuit punching converted to general ability, if melee_can_hit is TRUE by default.

2023-02-19 22:34 UTC, Sypsoti commented
General approval at the 2/19 staff meeting.

2023-02-23 07:56 UTC, Atermonera requested changes
I want to state for the record that I am being this nitpicky not out of malice towards you, but towards the old code you're bringing before me.

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +	if(internal_damage&MECHA_INT_CONTROL_LOST)
Spacing

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +	if(istype(T, /mob/living))
isliving

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +		if(src.occupant.a_intent == I_HURT || istype(src.occupant, /mob/living/carbon/brain)) //Brains cannot change intents; Exo-piloting brains lack any form of physical feedback for control, limiting th
isbrain

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +				if(temp)
```suggestion
				if(!istype(temp))
					return
				// dedent organ-smashing
```

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +								if(H.reagents.get_reagent_amount("carpotoxin") + force < force*2)
`[...] + force < force*2` is adding `force` to both sides

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +				switch(damtype)
This pains me to read but the only way I can conceive of fixing it is barely any more readable

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +			return
Early return

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +		if(src.occupant.a_intent == I_HURT || istype(src.occupant, /mob/living/carbon/brain)) // Don't smash unless we mean it
Flip this to an early return and dedent

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +					melee_can_hit = 1
This code concludes both sides of the isliving()

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +				src.visible_message("<font color='red'><b>[src.name] hits [T]</b></font>")
SPAN_DANGER()?

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +			src.visible_message("<font color='red'><b>[src.name] hits [T].</b></font>")
SPAN_DANGER()?

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/medical/odysseus.dm
>  		return 0
```suggestion
	. = ..()
	if(istype(H))
		if(H.glasses)
			occupant_message("<font color='red'>[H.glasses] prevent you from using [src] [hud]</font>")
		else
			H.glasses = hud
			H.recalculate_vis()

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/medical/serenity.dm
> +	if(..())
See my other suggestion about move_inside - actually hey wait just put this on `/obj/mecha/medical`, the code is duplicated between both medical mecha (Should the hud go on mecha/medical too?)

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/medical/serenity.dm
> +	..()
`return ..()`

2023-02-23 07:56 UTC, Atermonera commented on code/game/mecha/medical/serenity.dm
> +/obj/mecha/medical/serenity/melee_action(atom/T)
How much of this proc is copy pasted?

2023-03-04 19:53 UTC, Atermonera reviewed
The temp thing might be a regression but the others are just nits, this is pretty close to being good.

2023-03-04 19:53 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +				if(!istype(temp))
Temp... isn't an organ?

2023-03-04 19:53 UTC, Atermonera commented on code/game/mecha/mecha.dm
> +			return
(Move this to the top of the proc so its more distinct)

2023-03-04 19:53 UTC, Atermonera commented on code/game/mecha/medical/medical.dm
> +	return
`. = ..()`?

2023-03-04 21:44 UTC, Atermonera approved these changes

2023-03-04 21:44 UTC, merged