big heckin chonker ultragigamega-ears!!!!
PolarisSS13/Polaris pull request #8994
Opened 2023-02-25 18:44 UTC by Varlaisvea

Boosts the range at which certain races can hear whispers.
Default whisper hearing range is 1 (audible) / 5 (semi-audible). This is unchanged for most races... 

.. but Tajaran now have 2/6 (a boost of +1), and Teshari now have 4/7 (a boost of +3). This means they can hear your whispers from several tiles away. You cannot hide secrets from the big heckin chonker ultragigamega-ears.

unashamed teshari buff, teshari hiding in backpacks now make for fucking incredible spies.

2023-03-05 22:53 UTC, Atermonera commented
Staff input: Tune teshari to just +1 (same as taj) and this is fine. As a number, 3 tile range seems small, but in practice, that's actually a pretty significant distance to get away from the wallflowers.

2023-03-06 06:50 UTC, Varlaisvea commented
tesh now have two less ears and one less boosted whisper hearing range

2023-03-07 00:23 UTC, Greenjoe12345 commented
shame it has to be lowered down to the same level as taj :(

2023-03-09 02:44 UTC, Atermonera requested changes

2023-03-09 02:44 UTC, Atermonera commented on code/modules/mob/living/carbon/human/species/species.dm
> +	var/hearboost = 0 										//Whisper hearing sensitivity. Default is 1 (adjacent).
```suggestion
	var/hearboost = 0 										//Extra range on whisper hearing. 0 is adjacent.
```

2023-03-09 02:44 UTC, Atermonera commented on code/modules/mob/living/say.dm
>  						M.show_message("<span class='game say'><span class='name'>[name]</span> [w_not_heard].</span>", 2)
```suggestion
				if(dst <= min(message_range + M.hearing_boost_range(), world.view) || (M.stat == DEAD && !forbid_seeing_deadchat)) //Inside normal message range, boosted whisper range, or dead with ears (handled in the view proc)
					if(M.client && !runechat_enabled)
						var/image/I1 = listening[M] || speech_bubble
						images_to_clients[I1] |= M.client
						M << I1
					M.hear_say(message_pieces, verb, italics, src, speech_sound, sound_vol)
				if(whispering && !isobserver(M)) //Don't even bother with these unless whispering
					if(between, dst message_range + M.hearing_boost_range(), w_scramble_range + M.hearing_boost_range()) //Inside whisper scramble range
						if(M.client && !runechat_enabled)
							var/image/I2 = listening[M] || speech_bubble
							images_to_clients[I2] |= M.client
							M << I2
						M.hear_say(stars_all(message_pieces), verb, italics, src, speech_sound, sound_vol*0.2)
					if(between(dst, w_scramble_range + M.hearing_boost_range(), world.view) //Inside whisper 'visible' range
						M.show_message("<span class='game say'><span class='name'>[name]</span> [w_not_heard].</span>", 2)
```
This diff renders really messily but I'm basically proposing you make a proc on /mob to get the "hearing boost range", and override that on human mobs to get the species boost range. Drops the mess of `message_range_boosted` and `w_scramble_range_boosted`.
Check my syntax on `between()`, the order of arguments is out of my ass.

2023-03-12 19:44 UTC, Atermonera commented
It's `between(lower, middle, upper)` ftr, so the value that you're clamping is the middle arg. Which is really weird! And imo poor usability.

2023-03-12 19:46 UTC, Atermonera approved these changes

2023-03-12 19:46 UTC, merged