meson/nvg/thermal etc overlays can now be toggled
PolarisSS13/Polaris pull request #9019
Opened 2023-03-03 20:41 UTC by Varlaisvea

title

alt-click to toggle the cosmetic overlay on mesons, nvgs, thermals, gravitons, material scanners, science goggles
gameplay functionality is unchanged but now you can disable the overlays separately to the functionality if you get eye strain

2023-03-12 21:00 UTC, Atermonera commented
That eye-searing overlay is a balance measure, to give some disadvantage to just always running around with them on. Do you have a proposed alternative to discourage that behaviour?

2023-03-15 08:04 UTC, Atermonera commented
~~So what I'm hearing is we should make the goggles give eye damage to the _character_...~~
Also honestly I wear a wool jacket as a middle layer, and just walking around with an outerlayer on top of it it'll build up a decent static charge, to the point where every time I walk into work and take off my jacket to sit down at my desk, I'll touch my workstation to deliberately try to shock myself to discharge the static before I accidentally shock myself somewhere else...

I think I need to pitch this to more staff, now that I've had some time to actually think about this. It was brought up in passing at the last staff meeting as like a footnote at the very end of a particularly long meeting so there wasn't really an official discussion, just peoples' immediate takes. I might try to get opinions before the next staff meeting but can't make guarantees.

2023-03-15 09:08 UTC, Atermonera commented
Oh and while I'm lying here in bed, I dug through the commit history. The change that appears to have first I triduced the overlays (which does date to bay) didn't have much conversation at all, which means it'll be very hard to procure any original discussion for whatever insights it may offer

2023-03-16 06:34 UTC, Atermonera commented
Talked w/ some staff. Concerns are that...
* If you _can_ turn off the overlays, why would you use them at all?
* If people turn off the overlays, they will forget that they're wearing material scanners or NVGs and then go to weld and take a bunch of eye damage.
* It's nice diegetic effect of wearing something over your eyes and seeing something affect your vision.
Proposed alternatives are...
* Give mesons the same overlay as NVGs (Or otherwise recolor the mesons to still be _indicative_ without being _eyesearing_).
* Make the overlay a circular gradient, sorta like how the screen fades to white when you're near-death.
* Just remove the overlays wholesale.

I'm most keen on trying out the circular gradient, because that seems like the best overall solution to particular colors are bad. If you're not up to that, I'm much more partial to recoloring the meson overlay than to removing them. And if you _have_ to remove them, possibly just the removing the overlay for the mesons, since that's the most offensive.
I don't see any particular value in adding a toggle over just removing the overlays outright, because both options have the same practical effect.

2023-03-17 18:07 UTC, Varlaisvea commented
a circular gradient would honestly be really neat, i'm not sure how we'd go about doing it though tbh
as far as the fear of people forgetting they're wearing them and then welding their eyes goes... skill issue

2023-03-26 21:18 UTC, Atermonera requested changes
To be clear the staff input is that this will not be merged as-is, still waiting on you to propose another solution or implement one of the suggestions.

2023-03-27 08:41 UTC, Varlaisvea commented
will be faster to close this and remake it with the changes, stay tuned!

2023-03-27 08:41 UTC, closed without merging