Adding species-level flavours and refactoring how reagent flavour is handled.
PolarisSS13/Polaris pull request #9107
Opened 2023-05-27 15:05 UTC by MistakeNot4892

- Makes nutriment and taste_desc both write to reagent data.
- Makes reagent flavour use reagent data.
- Adds species-specific taste strings for Teshari.

**TODO:**
- [ ] Add Tesh strings for food nutriment desc.
- [ ] Integrate with Cereb's flavour branch.
- [ ] Test overhead from all the lists.

2023-05-28 19:09 UTC, Atermonera commented
Wait that's the wrong  button

2023-07-20 01:58 UTC, Cerebulon commented
The taste strings you have changed seem fine, but it seems like for Drinks you made "spicy" things taste different while for Food you only changed sweet things and left spicy things spicy. I don't mind either way, but it should probably be consistent tasting/not tasting Spice unless it was meant to just be differing interpretations of "strong alcohol" in which case hot noodles (drink) is an outlier.

2023-07-23 19:23 UTC, Cerebulon commented
Proceed With The Spicelessness

2023-07-23 20:33 UTC, Atermonera submitted a review, later dismissed

2023-08-30 10:32 UTC, Spookerton requested changes

2023-08-30 10:32 UTC, Spookerton commented on code/modules/projectiles/projectile/arc.dm
> +				splash.reagents.add_reagent("blood", 10,TASTE_DATA(list("blood_colour" = "#ec4940")))
taste data?

2023-08-30 10:32 UTC, Spookerton commented on code/modules/reagents/reagent_containers/blood_pack.dm
> +		reagents.add_reagent(reag_id, 200, TASTE_DATA(list("donor"=null,"viruses"=null,"blood_DNA"=null,"blood_type"=blood_type,"resistances"=null,"trace_chem"=null)))
taste data?

2023-08-30 10:32 UTC, Spookerton commented on code/modules/xenoarcheaology/effects/sweating_reagents.dm
> +		splash.reagents.add_reagent("blood", 10, TASTE_DATA(list("blood_colour" = effect_color)))
taste data?

2023-08-30 11:11 UTC, Spookerton approved these changes

2023-08-30 11:11 UTC, merged