Teshari agility toggle
PolarisSS13/Polaris pull request #9202
Opened 2023-08-07 23:25 UTC by Greenjoe12345

Ports the ability for teshari to toggle their agility from downstream, through a button in the abilities tab, when pressed, this toggles their PASSTABLE flag off and on.

2023-08-14 10:14 UTC, Spookerton requested changes

2023-08-14 10:14 UTC, Spookerton commented on code/modules/mob/living/living_powers.dm
> +	set name = "Toggle Agility" //Dunno a better name for this. You have to be pretty agile to hop over stuff!!!
```suggestion
	set name = "Toggle Agility"
```
Avoid waffle comments

2023-08-14 14:03 UTC, Spookerton approved these changes

2023-08-14 14:04 UTC, Spookerton commented
A separate movement intent can replace this if/when

2023-08-15 05:35 UTC, Atermonera approved these changes

2023-08-15 05:35 UTC, merged