Feature/poker chips
PolarisSS13/Polaris pull request #9238
Opened 2023-09-08 15:00 UTC by woody41

Hi,

this is PR where I would like to add new poker chips. This PR contains few new textures for tokens and one new texture for box as a holder of chips. cynosure-2 has change of spawn location of case with poker chips - library on table under d20. 

This is my first DM code ever and I don't know best practice, so if something is bad, let me know.

2023-09-08 20:55 UTC, woody41 commented on code/modules/economy/chip.dm
> +	desc = "It's worth 0 Chips."
it's just placeholder for init. You cannot have 0 value chip.

2023-09-10 13:47 UTC, Spookerton requested changes
also, needs squash

2023-09-10 13:47 UTC, Spookerton commented on maps/cynosure/cynosure-2.dmm
The dream maker editor isn't good and produces a format that's bad for git diffs -  mapping changes should be done with strongdmm instead:
https://github.com/SpaiR/StrongDMM/releases/tag/v2.8.1.alpha
or if that crashes:
https://github.com/SpaiR/StrongDMM/releases/tag/v1.9.1

2023-09-10 13:47 UTC, Spookerton commented on code/modules/economy/chip.dm
> +
avoid random empty lines

2023-09-10 13:47 UTC, Spookerton commented on code/modules/economy/chip.dm
> +	var/access = list()
unused var

2023-09-10 13:47 UTC, Spookerton commented on code/modules/economy/chip.dm
> +	var/worth = 0
I'm inclined to say this should be done with types, since these chips do not actually have a worth

2023-09-10 13:47 UTC, Spookerton commented
Regarding the above, I'll fix it up.

2023-09-10 15:57 UTC, Spookerton approved these changes

2023-09-10 16:08 UTC, merged

2023-09-15 05:37 UTC, woody41 commented
@Spookerton When you fixed the code you added a bug. Now you cannot take specific amount of poker chips, but you have to take each chip one by one. My code: When you click on chips you can select amount of worth what you want to take. No you have to select a specific value from predefined list. That's not good. I think it is caused by removing worth variable.