Demolishing Mobs
PolarisSS13/Polaris pull request #9264
Opened 2023-10-07 23:24 UTC by Mechoid

Space Worm given a maintenance pass.
- Able to charge toward a target, devouring objects or mobs in their path.
- Able to target mobs through walls, and damage many types of obstructions normally ignored by simple mobs. (Both are toggles on the AI datum.)

Thermic spiders given a "tactical" role for giant spiders, acting as breachers.
- Able to target mobs through walls, similar to the worm.
- Able to demolish walls and other common obstructions, similar to the worm.

Demolishing behavior does not instigate ally-calling as normal targeting does, unless the ally _also_ shares the ability to demolish.

2023-10-08 00:09 UTC, Cerebulon commented
I have some balance concerns about a mod which afaik is in the Random Spider Rotation for PoIs, being able to target and attack you through walls which it can also destroy? It seems like a thing which should be a special kind of mob and not just something which can totally alter a poi by randomly spawning?

2023-10-10 11:29 UTC, Spookerton commented
Doubt the 10% reduction addresses the concern; tagged for contention.

2023-11-27 03:44 UTC, Atermonera requested changes
Requesting subtypes of phorogenic & thermic that get demolishing, and are explicitly _not_ in the random spider spawn rotation.

2024-01-14 22:08 UTC, Atermonera commented on code/modules/ai/ai_holder_targeting.dm
> +			if(ignore_opacity || can_see(holder, HM, vision_range))
Do you mean AM?

2024-01-14 22:10 UTC, Atermonera approved these changes

2024-01-14 22:10 UTC, merged